name: Build and publish the nuget project

on:
  push:
    branches: 
      - main
      - 'release-*'
      - 'beta-release-*'
  pull_request:
    branches: 
      - main

jobs:
  build-csdk-win:
    if: "!contains(github.event.head_commit.message, 'ci skip') && ${{ github.actor != 'dependabot[bot]' && github.repository_owner == 'openziti' }}"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - if: github.event_name == 'push'
        run: echo "GIT_BRANCH=$($env:GITHUB_REF.replace('refs/heads/', ''))" >> $env:GITHUB_ENV
      - if: github.event_name == 'pull_request'
        run: echo "GIT_BRANCH=$env:GITHUB_HEAD_REF" >> $env:GITHUB_ENV
      - name: Create NuGet package
        run: ${{ github.workspace }}/create-nuget-package.bat
      - if: ${{ env.GIT_BRANCH == 'main' }} 
        name: Publish Ziti.NET.Standard
        run: dotnet nuget push Ziti.NET.Standard\Ziti.NET.Standard*.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json

