name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build-csdk-win:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: make build-win dir
        run: cmake -E make_directory ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-win
      - name: configure cmake
        run: cmake -S ${{ github.workspace }}/ZitiNativeApiForDotnetCore -B ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-win
      - name: build
        run: cmake --build ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-win --config Release
      - uses: actions/upload-artifact@v2
        with:
          name: ziti4dotnet-win.dll
          path: ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-win/Release/ziti4dotnet.dll
        
  build-csdk-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: make build-linux dir
        run: cmake -E make_directory ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-linux
      - name: configure cmake
        run: cmake -S ${{ github.workspace }}/ZitiNativeApiForDotnetCore -B ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-linux
      - name: build
        run: cmake --build ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-linux --config Release
      - uses: actions/upload-artifact@v2
        with:
          name: ziti4dotnet-linux.so
          path: ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-linux/Release/libziti4dotnet.so
        
  build-csdk-macos:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: make build-macos dir
        run: cmake -E make_directory ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-macos
      - name: configure cmake
        run: cmake -S ${{ github.workspace }}/ZitiNativeApiForDotnetCore -B ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-macos
      - name: build
        run: cmake --build ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-macos --config Release
      - uses: actions/upload-artifact@v2
        with:
          name: ziti4dotnet-macos.so
          path: ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-macos/Release/libziti4dotnet.so


