name: C/C++ CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build_csdk:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/upload-artifact@v2
        with:
          name: ziti4dotnet-${{ runner.os }}
      - name: make build dir
        run: cmake -E make_directory ${{runner.workspace}}/ZitiNativeApiForDotnetCore/build
      - name: configure cmake
        run: cmake -S ${{ github.workspace }}/ZitiNativeApiForDotnetCore -B ${{runner.workspace}}/ZitiNativeApiForDotnetCore/build
      - name: build
        run: cmake --build ${{runner.workspace}}/ZitiNativeApiForDotnetCore/build

  build_dotnet:
    runs-on: windows-latest
    steps:
      - uses actions/download-artifact@v2
