name: Build and publish ziti native libraries to nuget

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version of CSDK/Nuget Package
        default: 0.25.4
        required: true
env:
  ZITI_SDK_C_BRANCH: ${{ github.event.inputs.version }}
jobs:
  build-csdk-win:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Generate Native Libraries
        run: ${{ github.workspace }}/ZitiNativeApiForDotnetCore/msvc-build.bat
      - name: compile x86
        run: cmake --build ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-win/x86 --config Release
      - name: compile x64
        run: cmake --build ${{ github.workspace }}/ZitiNativeApiForDotnetCore/build-win/x64 --config Release
      - name: Pack Ziti.NET.Standard.native
        run: nuget pack native-package.nuspec -Version ${{ env.ZITI_SDK_C_BRANCH }}
      - name: Publish Ziti.NET.Standard.native
        run: nuget push Ziti.NET.Standard.native.${{ env.ZITI_SDK_C_BRANCH }}.nupkg -NonInteractive -ApiKey ${{secrets.NUGET_API_KEY}} -Source https://api.nuget.org/v3/index.json
